---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: url-shortener
spec:
  encryptedData:
    DATABASE_URL: AgBB+SZa6VN+auDJ5rYQvZAATpYdt0f3xx6jo68YEeDYDru2heeSNqNMt/X16JJlOFp+BBDKgK6D7Tckw012XZ+XIQ7IsjWbIIxZQAcrBPOTfK/YFfwFDrxx9xaDa7zuNvRid3lDOAmMhonAzheyiWXCPkyvPDJOzlf0YazYJM8NbDg7HgjTODIeo3lSGE62V2MTEN0ds0lTDCkucti1zJpA9zNoV6RgEGr0beZR1FpCWAjgo+XQ9MGUcFJFdwDJHQumWjqFiSYtYvadKfgK2vnLBSboEgThifcmTAfz3fjWHYGrG3o4bv0wuItsYLroWxOib3qxfkmkAVpcN4SFrqGgWtLigrD266BuFZ7L3AcXyJTflsMqdpQtSIYLuvpaOL2md1ebc6HfhKxE1Q0ElP09JZ0+6GfvKVAF0X7QxRSv0qjkIMGngOvCietAAgiieowzHDiy8/K7MZk/7/qt+ISwHgtGsnt+hsELwKmxivEqvGy9Qt6XybbDn/BWysbt7reMY6mzvplBv4Fpa4QPVVVBFIf/m9wQX41SyHEcVBV6jANNOWZyMSobySf9hQ7J7y+8UE1MgKEqKtvMQOI1gr6bAABYLTx/hcCi8Rod09IOVpEiKaHw3ibSGF4JICqD6tjb50dR4kDdpoDG83FiY2bBQsvMhat7iZbmKZCITf+Kv0dFc2vEamb6wtHktlNiAblZzrDU65T51DqNb5QDhNAmOCUL3WbhwL3rqJy3wInzsto5YyQeMakQN8qDJiI0FXiXqbvytSZbY68vFTo73QCePYJHZYX3e4U9WyOFi/5yCZQ=
  template:
    metadata:
      name: app-secret
      namespace: url-shortener
